title: Adedayo Odumosu
logo: /Logo_DA.jpeg
description: A data analyst with over 5 years of experience, proficient with tools like Excel, SQL and Power BI
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
